import LegalLayout from '@/components/shared/LegalLayout';

export const metadata = {
    title: 'Privacy Policy — PlacementOS',
    description: 'How PlacementOS collects, uses, and protects your personal data.',
};

const S = ({ children }) => (
    <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '22px', fontWeight: 700, color: 'var(--text)', marginTop: '40px', marginBottom: '12px' }}>
        {children}
    </h2>
);
const P = ({ children }) => (
    <p style={{ marginBottom: '16px', color: 'var(--text-muted)', lineHeight: 1.9 }}>{children}</p>
);
const Li = ({ children }) => (
    <li style={{ marginBottom: '8px', color: 'var(--text-muted)', lineHeight: 1.85, paddingLeft: '6px' }}>{children}</li>
);

export default function PrivacyPolicy() {
    return (
        <LegalLayout title="Privacy Policy" lastUpdated="March 2, 2026">

            <P>This Privacy Policy explains how <strong>PlacementOS</strong> ("we", "us", or "our"), operated by TechForce Studio, collects, uses, stores, and protects information obtained from users ("you", "user") of our platform at <strong>www.placementos.in</strong> and any related subdomains. By using PlacementOS, you agree to the terms of this Privacy Policy.</P>

            <S>1. Information We Collect</S>
            <P>We collect information you provide directly, information generated by your use of our platform, and information from third-party services you connect with:</P>
            <ul style={{ paddingLeft: '22px', marginBottom: '20px' }}>
                <Li><strong>Account Data:</strong> Name, email address, and profile image, collected via Clerk authentication (Google/email sign-in).</Li>
                <Li><strong>Portfolio Content:</strong> Projects, certificates, achievements, skills, education records, resume data, bio, and headline that you add to your portfolio.</Li>
                <Li><strong>Uploaded Media:</strong> Images and files you upload for projects, certificates, and achievements. These are stored securely via our cloud file storage provider.</Li>
                <Li><strong>Usage Data:</strong> Pages visited, features accessed, browser type, IP address, device information, and timestamps, collected automatically for security and platform improvement.</Li>
                <Li><strong>Communications:</strong> Any emails or messages you send to our support team.</Li>
            </ul>

            <S>2. How We Use Your Information</S>
            <ul style={{ paddingLeft: '22px', marginBottom: '20px' }}>
                <Li>To create and manage your PlacementOS account and portfolio.</Li>
                <Li>To enable premium features such as PDF export and public shareable portfolio links (unlocked by sharing).</Li>
                <Li>To send you transactional emails (account activation, updates, expiry reminders).</Li>
                <Li>To monitor and prevent fraudulent or abusive use of the platform.</Li>
                <Li>To improve platform performance, security, and user experience.</Li>
                <Li>To comply with applicable legal obligations under Indian law.</Li>
            </ul>

            <S>3. Public Portfolio Visibility</S>
            <P>Users who unlock premium features by sharing may generate a publicly shareable link to their portfolio. <strong>When you enable a public portfolio link, the content of your portfolio — including your name, projects, certificates, achievements, and any other information you have added — becomes accessible to anyone with that link without requiring login.</strong> You are solely responsible for the content you choose to publish publicly. You may disable the public link at any time from your dashboard, at which point the portfolio will no longer be publicly accessible.</P>

            <S>4. Third-Party Services</S>
            <P>PlacementOS integrates with the following third-party services. Each operates under its own privacy policy:</P>
            <ul style={{ paddingLeft: '22px', marginBottom: '20px' }}>
                <Li><strong>Clerk (clerk.com):</strong> Authentication and user identity management.</Li>
                <Li><strong>MongoDB Atlas:</strong> Database for storing user portfolio data.</Li>
                <Li><strong>Cloud Storage (e.g., Cloudinary / UploadThing):</strong> Storage for user-uploaded files and images.</Li>
            </ul>

            <S>5. Data Retention</S>
            <P>We retain your data for as long as your account remains active. Free-tier user data is subject to an expiry policy (visible in your dashboard). Premium user data (unlocked by sharing) is retained as long as your account is active, unless you request earlier deletion.</P>

            <S>6. Data Security</S>
            <P>We implement industry-standard security measures including HTTPS encryption, access-controlled databases, and secure authentication via Clerk. However, no method of transmission over the internet is 100% secure. We cannot guarantee absolute security of data transmitted to or stored on our platform.</P>

            <S>7. Your Rights</S>
            <P>You have the right to: (a) access and download your personal data; (b) request correction of inaccurate data; (c) request deletion of your account and associated data; (d) withdraw consent for optional data processing. To exercise any of these rights, contact us at <strong>support@placementos.in</strong>.</P>

            <S>8. Cookies</S>
            <P>PlacementOS uses session cookies for authentication (managed by Clerk) and local storage for theme preferences. We do not use advertising cookies or third-party tracking cookies.</P>

            <S>9. Children's Privacy</S>
            <P>PlacementOS is not directed to individuals under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us immediately at <strong>support@placementos.in</strong>.</P>

            <S>10. Changes to This Policy</S>
            <P>We may update this Privacy Policy periodically. Material changes will be communicated via email or in-platform notification. Continued use of PlacementOS after such updates constitutes acceptance of the revised policy. The effective date at the top of this document will reflect the latest version.</P>

            <S>11. Contact</S>
            <P>For any privacy-related questions or requests, contact: <br /><strong>Email:</strong> support@placementos.in<br /><strong>Operated by:</strong> TechForce Studio, India</P>

        </LegalLayout>
    );
}
