import mongoose from 'mongoose';

const ResumeDataSchema = new mongoose.Schema({
    label: { type: String, default: 'Resume 1' },
    isActive: { type: Boolean, default: false },
    templateId: { type: Number, default: 1 },
    accentColor: { type: String, default: '#2D6A4F' },
    personalInfo: {
        name: { type: String, default: '' },
        email: { type: String, default: '' },
        phone: { type: String, default: '' },
        location: { type: String, default: '' },
        linkedinUrl: { type: String, default: '' },
        githubUrl: { type: String, default: '' },
        leetcodeUrl: { type: String, default: '' },
        portfolioUrl: { type: String, default: '' },
        websiteUrl: { type: String, default: '' },
        profilePicUrl: { type: String, default: '' },
        name_hidden: { type: Boolean, default: false },
        email_hidden: { type: Boolean, default: false },
        phone_hidden: { type: Boolean, default: false },
        location_hidden: { type: Boolean, default: false },
        linkedinUrl_hidden: { type: Boolean, default: false },
        githubUrl_hidden: { type: Boolean, default: false },
        leetcodeUrl_hidden: { type: Boolean, default: false },
        portfolioUrl_hidden: { type: Boolean, default: false },
    },
    summary: { type: String, default: '' },
    skillsText: { type: String, default: '' },
    skills: [{ type: String }],
    education: [{
        institution: { type: String, default: '' },
        university: { type: String, default: '' },
        degree: { type: String, default: '' },
        field: { type: String, default: '' },
        startYear: { type: String, default: '' },
        endYear: { type: String, default: '' },
        grade: { type: String, default: '' },
        gradeType: { type: String, default: 'CGPA' },
        description: { type: String, default: '' },
        hidden: { type: Boolean, default: false },
    }],
    experience: [{
        company: { type: String, default: '' },
        role: { type: String, default: '' },
        startDate: { type: String, default: '' },
        endDate: { type: String, default: '' },
        current: { type: Boolean, default: false },
        description: { type: String, default: '' },
    }],
    projects: [{
        title: { type: String, default: '' },
        description: { type: String, default: '' },
        techStack: [{ type: String }],
        githubUrl: { type: String, default: '' },
        demoUrl: { type: String, default: '' },
        startDate: { type: String, default: '' },
        endDate: { type: String, default: '' },
        hidden: { type: Boolean, default: false },
    }],
    achievements: [{
        title: { type: String, default: '' },
        description: { type: String, default: '' },
        year: { type: String, default: '' },
        url: { type: String, default: '' },
    }],
    hobbies: [{ type: String }],
    certifications: [{
        title: { type: String, default: '' },
        description: { type: String, default: '' },
        year: { type: String, default: '' },
        url: { type: String, default: '' },
        hidden: { type: Boolean, default: false },
    }],
    leadership: [{
        role: { type: String, default: '' },
        organization: { type: String, default: '' },
        description: { type: String, default: '' },
        startDate: { type: String, default: '' },
        endDate: { type: String, default: '' },
    }],
    languages: [{ type: String }],
    interests: [{ type: String }],
    references: { type: String, default: '' },
    boldSkillsHeader: { type: Boolean, default: false },
    showProfilePic: { type: Boolean, default: false },
    atsSymbols: { type: Boolean, default: true },
    atsStandardSectionNames: { type: Boolean, default: false },
    atsConsistentFormatting: { type: Boolean, default: false },
    atsSingleColumn: { type: Boolean, default: false },
    atsFontSelection: { type: String, default: '' },
    atsProfileLinksFormat: { type: Boolean, default: false },
    atsProjectLinksFormat: { type: Boolean, default: false },
    updatedAt: { type: Date, default: Date.now },
});

const UserResumesSchema = new mongoose.Schema({
    userId: { type: String, required: true, unique: true },
    resumes: {
        type: [ResumeDataSchema],
        default: [],
        validate: [arr => arr.length <= 3, 'Maximum 3 resumes allowed'],
    },
});

if (mongoose.models.UserResumes) {
    delete mongoose.models.UserResumes;
}

export default mongoose.model('UserResumes', UserResumesSchema, 'resumes');
